config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :dresses do
    resources :bookings, only:[ :new, :create ]
    resources :reviews, only: [ :new, :create ]
  end

  resources :bookings, only:[ :index, :destroy ]
  resources :reviews, only:[ :destroy ]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :dress
  belongs_to :user
  validates :start_date, presence: true
  validates :end_date,presence: true
end

app/models/dress.rb
class Dress < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :price, presence:true
  validates :category, presence:true
  validates :size, presence: true
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :dress
  belongs_to :user
  validates :rating, presence: true
  validates :content, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
  end

  def new
    @dress = Dress.find(params[:dress_id])
    @booking = Booking.new
  end

  def create
    @dress = Dress.find(params[:dress_id])
    @booking = Booking.new(booking_params)
    @booking.dress = @dress
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path
    else
      render "dresses/show", dress: @dress
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end


  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

end

app/controllers/dresses_controller.rb
class DressesController < ApplicationController
  before_action :find_dress, only: [:show, :edit,:update,:destroy]

  def index
    @dresses = Dress.geocoded
    @markers = @dresses.map do |dress|
      {
        lat: dress.latitude,
        lng: dress.longitude
      }
    end
  end

  def show
    @dresses = Dress.all.where(category: @dress.category).where.not(id: @dress.id)
  end

  def new
    @dress = Dress.new
  end

  def create
    @dress = Dress.new(dress_params)
    if @dress.save
      redirect_to dress_path(@dress)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @dress.update(dress_params)
    redirect_to dress_path(@dress)
  end

  def destroy
    @dress.destroy
    redirect_to dresses_path
  end

  private
  def find_dress
    @dress = Dress.find(params[:id])
  end

  def dress_params
    params.require(:dress).permit(:name, :price, :category,:size, :photo, :address)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]
  def home
    flash[:notice] = "Welcome and Happy renting dress ❤️"
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @dress = Dress.find(params[:dress_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @dress = Dress.find(params[:dress_id])
    @review.dress = @dress
    @review.user_id = current_user.id

    if @review.save
      redirect_to dress_path(@dress)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to dresses_path
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class= "head">
  <h1>My Bookings</h1>
</div>

<div class="bookings-container">
  <% @bookings.each do |booking| %>
    <% days = (booking.end_date - booking.start_date).to_i %>

    <div class="booking-card">
      <div class="booking-photo">
        <p><%= cl_image_tag booking.dress.photo.key %></p>
      </div>

      <div class="booking-details">
        <p class= booking-head><%= booking.dress.name %></p>
        <p>Category: <%= booking.dress.category %></p>
        <p>Price: £<%= (booking.dress.price) * days %></p>
        <p>Size: <%= booking.dress.size %></p>
        <p>Start Date: <%= booking.start_date %></p>
        <p>End Date: <%= booking.end_date %></p>
        <p>Total Days: <%= days %></p>
        <%= link_to booking_path(booking),method: :delete do%>
        <i class="bin fas fa-trash-alt"></i>
      <% end %>
      </div>
    </div>
  <% end %>
</div>

<button class= 'dress-index'><%= link_to "Back", dresses_path %></button>

app/views/bookings/new.html.erb
<h2>Add Booking</h2>
<%= simple_form_for [@dress, @review, @booking] do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>


<%= link_to "Back", dress_path(@dress) %>

<%= link_to "booking page", bookings_path %>

app/views/dresses/_dress_carousel.html.erb
<div class="container my-4">

  <!--Carousel Wrapper-->
  <div id="multi-item-example" class="carousel slide carousel-multi-item" data-ride="carousel">

    <!--Controls-->
    <div class="controls-top">
      <a class="btn-floating" href="#multi-item-example" data-slide="prev"><i class="fa fa-chevron-left"></i></a>
      <a class="btn-floating" href="#multi-item-example" data-slide="next"><i class="fa fa-chevron-right"></i></a>
    </div>
    <!--/.Controls-->

    <!--Indicators-->
    <ol class="carousel-indicators">
      <li data-target="#multi-item-example" data-slide-to="0" class="active"></li>
      <li data-target="#multi-item-example" data-slide-to="1"></li>
      <li data-target="#multi-item-example" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <% dresses.in_groups_of(3).each_with_index do |dress_array, i| %>
        <div class="carousel-item <%= 'active' if i.zero? %>">
          <div class="row">
            <% dress_array.each do |dress| %>
              <% next unless dress %>
              <%= link_to dress_path(dress),class:"card-link" do%>
              <div class="col-md-4">
                <div class="card mb-2">
                  <%= cl_image_tag dress.photo.key, class: "small-image" %>
                  <div class="card-body">
                    <h4 class="card-title"><%= dress.name  %></h4>
                    <p class="card-text">£<%= dress.price %></p>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <!--/.Slides-->
  </div>
  <!--/.Carousel Wrapper-->
</div>

app/views/dresses/edit.html.erb
<h3>Edit the dress </h3>
<%= simple_form_for(@dress) do |f| %>
<%= f.input :name %>
<%= f.input :size, collection: ["UK 4","UK 6","UK 8","UK 10","UK 12","UK 14","UK 16"] %>
<%= f.input :price %>
<%= f.input :address %>
<%= f.input :photo, as: :file %>
<%= f.input :category, collection: Dress.pluck(:category).uniq %>
<%= f.submit 'edit dress!' %>
<% end %>
<%= link_to "Dress index page", dresses_path %>

app/views/dresses/index.html.erb
<h2 class="index-heading">All Dresses</h2>
<div class="grid-with-map">
  <div class="grid-index">
    <% @dresses.each do |dress| %>
      <div class="dress-index-card">

        <% if dress.photo.attached? %>
        <div class="dress-index-image text-center grid-photo">
          <%= link_to dress_path(dress) do %>
            <%= cl_image_tag dress.photo.key, height: 350, width: 250, crop: :fill %>
          <% end %>
        </div>
        <% else %>
        <% end %>

        <div class="dress-index-info text-center">
        <%= link_to dress.name, dress_path(dress) %>
        </br>
        <p>£ <%= dress.price %></p>
        </div>
      </div>
      <% end %>
    </div>

    <div id="map"
      style="height: 500px !important; width: 300px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

</div>

<!-- end of file -->

app/views/dresses/new.html.erb
<div class="d-flex justify-content-center">
   <h3 class="header p-4">Upload your dress! </h3>
</div>

<div class="d-flex justify-content-center">

  <%= simple_form_for(@dress) do |f| %>
  <%= f.input :name %>
  <%= f.input :size, collection: ["UK 4","UK 6","UK 8","UK 10","UK 12","UK 14","UK 16"] %>
  <%= f.input :price %>
  <%= f.input :address %>
  <%= f.input :category, collection: Dress.pluck(:category).uniq %>
  <%= f.input :photo, as: :file %>

  <div class="d-flex justify-content-center">
      <%= f.submit 'Create new dress!',  class: "btn btn-outline-dark  mb-3" %>
      <% end %>
  </div>
</div>

<div class="d-flex justify-content-center">
    <%= link_to "Go back", dresses_path, class: "btn btn-link" %>
</div>

app/views/dresses/show.html.erb
<div class="container pb-5">
    <!-- image and description -->
    <div class="grid">
    <div class="dress-all">

      <div class="dress-image-show">
        <%= cl_image_tag @dress.photo.key,height: 500, width: 350, crop: :fill, data: {toggle: "modal", target: "#exampleModal"} %>
        </div>
        <div class="dress-info mt-3">
          <h5 class="pb-4"><%= @dress.name %></h5>
            <p><b>Price:</b> £<%= @dress.price %></p>
            <p><b>Category:</b> <%= @dress.category %></p>
            <p><b>Size:</b> <%= @dress.size%></p>
        </div>
      </div>
    <!-- booking form and button -->
    <div class="booking-all">
      <h2 class="pb-4">Book this dress</h2>
        <%= simple_form_for [@dress, Booking.new] do |f| %>
          <%= f.input :start_date, as: :date, html5:true, input_html: { value: Date.today } %>
          <%= f.input :end_date,as: :date, html5:true, input_html: { value: Date.today + 1 } %>
          <%= f.submit class: "btn btn-light mt-3 create-booking-button" %>
      <% end %>


      <div class="show-ratings pt-5">
        <h3>User Reviews</h3>
          <% @dress.reviews.each do |review|%>
          <p></p>
            <div class="border ratings-table">
              <p><%= "⭐" * (review.rating.to_i) %></p>
              <p><%= review.content %></p>
            </div>
          <% end %>
        </div>

      <% if Booking.where(dress: @dress).where(user: current_user).any? %>
        <h3 class="pt-5">Add Review</h3>
          <%= simple_form_for [@dress, Review.new] do |f| %>
            <%= f.input :rating, collection: 1..5  %>
            <%= f.input :content %>
            <%= f.submit class: "btn btn-light mt-3 mb-5 create-booking-button" %>
          <% end %>
      <% end %>
    </div>

      <div><h2>You may also like...</h2></div>
      <br>
      </div>
      <%= render "dress_carousel", dresses: @dresses, original_dress: @dress %>

      </div>
</div>

  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= @dress.name %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= cl_image_tag @dress.photo.key, class: "modal-img-w" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentDress</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <h1>Rent my dress</h1>
  <p>Never wear the same thing twice.</p>
  <button type="button" class="btn btn-outline-light home-button"><%= link_to "Pick Now", dresses_path %></button>
</div>

<div class="description">
  <h2>Find your next night out dress.</h2>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam at hic nulla necessitatibus modi, ipsam eaque sed beatae error consectetur tenetur ducimus iure fuga saepe, deserunt laudantium reprehenderit eligendi cum.</p>
</div>

<div class="container">
  <div class="row">
    <div class="col-4 text-center">
      <%= link_to dresses_path do %>
        <%= image_tag 'black_dress.jpg', class: 'dress-img'%>
        <h3 class= "subtitle">For Party...</h3>
      <% end %>
    </div>

    <div class="col-4 text-center">
      <%= link_to dresses_path do %>
      <%= image_tag 'bridesmaid_dress.jpg', class: 'dress-img'%>
      <h3 class= "subtitle">For Wedding...</h3>
      <% end %>
    </div>

    <div class="col-4 text-center">
      <%= link_to dresses_path do %>
      <%= image_tag 'grey_dress.jpg', class: 'dress-img'%>
      <h3 class= "subtitle">For Date...</h3>
      <% end %>
    </div>
  </div>
</div>


<div class="third-container">


</div>

app/views/reviews/new.html.erb
<h2>Add Review</h2>


<%= simple_form_for [@dress, @review] do |f| %>
  <%= f.input :rating, collection: 1..5  %>
  <%= f.input :content %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>


<%= link_to "Back", dress_path(@dress) %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>

<div class="navbar navbar-expand-sm navbar-lewagon" <%= 'style=position:absolute;background:rgba(26,23,23,0.4)' if params[:action] == 'home' %>>
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "dress_logo.png" %>
  <% end %>


    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Collection", dresses_path, class: "nav-link" %>
      </li>
    </ul>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "My Bookings", bookings_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Your Dress", new_dress_path, class: "nav-link" %>
      </li>

      <li class="nav-item dropdown">
        <%= image_tag "cara.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right dropdown-items" id="dropdown-text" aria-labelledby="navbarDropdown">
          <%= link_to "Settings", "#", class: "dropdown-item", style:'color:black' %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item", style:'color:black' %>
        </div>
      </li>
    </ul>
  </div>
</div>


<!-- repetition -->

<% else %>

<div class="navbar navbar-expand-sm navbar-lewagon" <%= 'style=position:absolute;background:rgba(26,23,23,0.4)' if params[:action] == 'home' %>>
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "dress_logo.png" %>
  <% end %>

    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Dresses", dresses_path, class: "nav-link" %>
      </li>

    </ul>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "My Bookings", bookings_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Add Dress", new_dress_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Login", user_session_path, class: "nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
      </li>



    </ul>
  </div>
</div>

<% end %>